apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-v1.0
  namespace: mark
  labels:
    functionGroup: simple-web
    service: simple-web-service
    deployedby: mark
    version: "1.0"
spec:
  selector:
    matchLabels:
      functionGroup: simple-web
      service: simple-web-service
      version: "1.0"
      deploymentTag: "1.0"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      annotations:
        tags: simple-web-service
      labels:
        functionGroup: simple-web
        service: simple-web-service
        version: "1.0"
        deploymentTag: "1.0"
    spec:
      containers:
        - name: simple-web
          image: acrinterview.azurecr.io/simple-web
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_ENV
              value: production
          ports:
            - name: server-port
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "512Mi"
              cpu:    "100m"
            limits:
              memory: "512Mi"
              cpu:    "200m"
