apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: simple-web-1.0
  namespace: mark
  labels:
    functionGroup: simple-web
    service: simple-web-service
    deployedby: mark
    version: "1.0"
    wait: "false"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simple-web-1-0
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
