apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: "mark"
  name:  {{ template "helm-chart-test.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  rules:
   - http:
      paths:
      - path: /mark
        pathType: Prefix
        backend:
          service:
            name: {{ template "helm-chart-test.fullname" . }}-local
            port:
              number: 80
