apiVersion: v1
kind: Service
metadata:
  name: simple-web-markp-1-0
  namespace: mark
  labels:
    functionGroup: simple-web
    service: simple-web-service
    deployedby: markp
    version: "1.0"
    wait: "false"
spec:
  selector:
    functionGroup: simple-web
    service: simple-web-service
    version: "1.0"
    deploymentTag: "1.0"
  ports:
    - protocol: TCP
      port: 80
      targetPort: server-port
  type: LoadBalancer
