apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm-chart-test.fullname" . }}-local
  namespace: mark
spec:
  selector:
    functionGroup: simple-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

